/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package words;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import words.TempWindow;
/**
 *
 * @author Beteab Gebru
 */
public class MyFrame extends JFrame implements ActionListener {

	private JLabel WordAnalyser = new JLabel("Word Analyser");
	private JButton SelectFIle = new JButton("Push me!");
	
	public MyFrame() 
        {
            this.setBounds(20, 200, 100, 50);
            this.setTitle( "My Frame");
            this.getContentPane().setLayout(null);
            
            WordAnalyser.setBounds(10, 35, 60, 12);
            this.getContentPane().add(WordAnalyser);
            
            SelectFIle.setBounds(10, 5, 50, 20);
            this.getContentPane().add(SelectFIle);
            SelectFIle.addActionListener( this);
	}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
	public void actionPerformed(ActionEvent e) {
		// TODO Auto-generated method stub
		System.out.println("Button pushed");
		this.SelectFIle.setText("Pushed");
	}
    
}
