/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package words;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;
import words.MyFrame;
/**
 *
 * @author Beteab Gebru
 */
public class TempWindow extends JFrame {
    
    JButton convertButton = new JButton( "Convert");
    JTextField fahrTemp = new JTextField( 20);
    JLabel fahrLabel = new JLabel( "Fahrenheit:");
    JLabel celLabel = new JLabel( "Celcius:");
    JLabel answer = new JLabel ( "Unknown");
    
    JButton fileButton = new JButton( "Which File?");
    
    public TempWindow() {
        this.setTitle("Temp Application");
        this.setBounds( 200, 300, 250, 150);
        this.getContentPane().setLayout(null);
        this.setDefaultCloseOperation( JFrame.EXIT_ON_CLOSE);
        
        this.convertButton.setBounds(10, 80, 100, 30);
        this.getContentPane().add( convertButton);
        this.convertButton.addActionListener( new ButtonListener());
        
        this.fahrTemp.setBounds( 120, 20, 100, 30);
        this.getContentPane().add( fahrTemp);

        this.fahrLabel.setBounds(10, 20, 100, 30);
        this.getContentPane().add( fahrLabel);

        this.celLabel.setBounds(10, 60, 100, 30);
        this.getContentPane().add( celLabel);
        
        this.answer.setBounds(120, 60, 100, 30);
        this.getContentPane().add( answer);
        
        this.fileButton.setBounds(120, 80, 100, 30);
        this.getContentPane().add(fileButton);
        this.fileButton.addActionListener( new FileButtonListener());
        

    }
    private void theButtonHasBeenPushed() {
        String text = fahrTemp.getText();
        double f = 0.0;
        try {
            f = Double.parseDouble(text);
        }
        catch( Exception e) {
            
        }
        double c = convertF2C( f);
        String cString = "" + c;
        this.answer.setText(cString);
        
    }
    

    private double convertF2C(double f) {
        double answer = (f - 32) * 5.0 / 9.0 ;
        return answer;
    }
    
    private class ButtonListener implements ActionListener {
        
        @Override
        public void actionPerformed( ActionEvent e) {
            TempWindow.this.theButtonHasBeenPushed();
        }
    }
    
    private class FileButtonListener implements ActionListener {
        @Override
        public void actionPerformed( ActionEvent e) {
            System.out.println("hit the file button");
            JFileChooser chooser = new JFileChooser();
            chooser.setFileFilter( new FileNameExtensionFilter("TEXT FILES", "txt", "text"));
            System.out.println("I created the file chooser");
            int chooserSuccess = chooser.showOpenDialog( null);
            System.out.println("I opended the file chooser, it returned " + chooserSuccess);
            if( chooserSuccess == JFileChooser.APPROVE_OPTION) {
                File chosenFile = chooser.getSelectedFile();
                // Pass this file to your function
                System.out.println("You chose the file " + chosenFile.getAbsolutePath());
                System.out.println("You chose the file " + chosenFile.getName());
            }
            else {
                System.out.println("You hit cancel");
            }
        }
    }
}



    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
